spring:
  application:
    name: site-processor
  pagination:
    default:
      page: 0
      size: 10
  data:
    redis:
      prefix-key: site
      ttl-seconds: 3600
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      repositories:
        enabled: false

  cloud:
    gcp:
      project-id: local-project
      core:
        credentials:
          enabled: false
      pubsub:
        emulator-host: ${PUBSUB_EMULATOR_HOST:localhost:8085}
        topic:
          site-events: site-events
      firestore:
        emulator:
          enabled: true
        host-port: ${FIRESTORE_EMULATOR_HOST:localhost:8695}
        project-id: local-project
